[package]
name = "naos-webdav"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-stream.workspace = true
axum.workspace = true
base64.workspace = true
http-body-util.workspace = true
naos-core = { path = "../naos-core" }
percent-encoding.workspace = true
serde.workspace = true
tokio.workspace = true
ulid.workspace = true

[dev-dependencies]
naos-store = { path = "../naos-store" }
sqlx.workspace = true
tempfile.workspace = true
tower.workspace = true
