[package]
name = "naos-nfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
system-gss = ["dep:libgssapi", "dep:windows-sys"]

[dependencies]
hmac.workspace = true
fs2.workspace = true
filetime.workspace = true
naos-core = { path = "../naos-core" }
rand_core.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libgssapi = { version = "0.11", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, optional = true, features = [
    "Win32_Foundation",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Credentials",
] }

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true
