#!/usr/bin/env bash
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "real Samba smoke test must run as root" >&2
  exit 2
fi

for command in smbd smbpasswd smbclient testparm setsid; do
  command -v "$command" >/dev/null
done

ROOT="$(mktemp -d)"
USER_NAME="naos_ci_smb"
GROUP_NAME="naos-users"
PASSWORD="naos-ci-password-$(date +%s)-$$"
PORT=1445
SMBD_PID=""

cleanup() {
  if [[ -n "$SMBD_PID" ]] && kill -0 "$SMBD_PID" 2>/dev/null; then
    kill "$SMBD_PID" 2>/dev/null || true
    wait "$SMBD_PID" 2>/dev/null || true
  fi
  smbpasswd -x -c "$ROOT/smb.conf" "$USER_NAME" >/dev/null 2>&1 || true
  userdel "$USER_NAME" >/dev/null 2>&1 || true
  rm -rf "$ROOT"
}
trap cleanup EXIT

getent group "$GROUP_NAME" >/dev/null || groupadd --system "$GROUP_NAME"
if getent passwd "$USER_NAME" >/dev/null; then
  echo "test account already exists: $USER_NAME" >&2
  exit 3
fi
useradd -M -s /usr/sbin/nologin -g "$GROUP_NAME" -c "Managed by naos" "$USER_NAME"

mkdir -p "$ROOT"/{cache,lock,private,state,share}
chmod 700 "$ROOT/private"
chown "$USER_NAME:$GROUP_NAME" "$ROOT/share"
chmod 770 "$ROOT/share"

cat >"$ROOT/naos-shares.conf" <<EOF
# NAOS MANAGED SAMBA SHARES v1
# Generated by naos. Manual edits will be replaced.

[ci-share]
    path = $ROOT/share
    browseable = yes
    read only = no
    guest ok = no
    valid users = @$GROUP_NAME
    inherit acls = yes
EOF

cat >"$ROOT/smb.conf" <<EOF
[global]
    server role = standalone server
    security = user
    smb ports = $PORT
    interfaces = 127.0.0.1
    bind interfaces only = yes
    disable netbios = yes
    map to guest = never
    passdb backend = tdbsam
    pid directory = $ROOT
    lock directory = $ROOT/lock
    state directory = $ROOT/state
    cache directory = $ROOT/cache
    private dir = $ROOT/private
    log file = $ROOT/log.%m

# BEGIN NAOS MANAGED SAMBA INCLUDE
include = $ROOT/naos-shares.conf
# END NAOS MANAGED SAMBA INCLUDE
EOF

testparm -s "$ROOT/smb.conf" >/dev/null

printf '%s\n%s\n' "$PASSWORD" "$PASSWORD" |
  smbpasswd -s -a -c "$ROOT/smb.conf" "$USER_NAME" >/dev/null

setsid smbd -F -s "$ROOT/smb.conf" -p "$PORT" </dev/null >"$ROOT/smbd.stdout" 2>&1 &
SMBD_PID=$!

smbclient_secure() {
  local client_command="$1"
  exec 3<<<"$PASSWORD"
  PASSWD_FD=3 smbclient "//127.0.0.1/ci-share" -p "$PORT" -U "$USER_NAME" -c "$client_command"
  local status=$?
  exec 3<&-
  return "$status"
}

READY=0
for _ in $(seq 1 50); do
  if ! kill -0 "$SMBD_PID" 2>/dev/null; then
    echo "smbd exited before becoming ready" >&2
    cat "$ROOT/smbd.stdout" >&2 || true
    exit 5
  fi
  if smbclient_secure 'ls' >/dev/null 2>&1; then
    READY=1
    break
  fi
  sleep 0.1
done

if [[ "$READY" -ne 1 ]]; then
  echo "smbd did not become ready on port $PORT" >&2
  cat "$ROOT/smbd.stdout" >&2 || true
  exit 6
fi

printf 'hello from naos samba smoke\n' >"$ROOT/local.txt"
smbclient_secure "put $ROOT/local.txt uploaded.txt; get uploaded.txt $ROOT/downloaded.txt; rename uploaded.txt renamed.txt; del renamed.txt" >/dev/null

cmp "$ROOT/local.txt" "$ROOT/downloaded.txt"
if [[ -e "$ROOT/share/renamed.txt" || -e "$ROOT/share/uploaded.txt" ]]; then
  echo "SMB cleanup operation did not remove test file" >&2
  exit 4
fi

echo "real Samba read/write/rename/delete smoke test passed"
